# Generated by Django 5.0.1 on 2026-01-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(blank=True, max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("government", "Government"),
                            ("intergovernmental", "Intergovernmental"),
                            ("regulator", "Regulator"),
                            ("court", "Court"),
                            ("research_center", "Research Center"),
                            ("university", "University"),
                            ("law_firm", "Law Firm"),
                            ("consulting_firm", "Consulting Firm"),
                            ("think_tank", "Think Tank"),
                            ("standards_body", "Standards Body"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=600)),
                ("landing_page_url", models.URLField(blank=True, max_length=2000)),
                ("report_url", models.URLField(blank=True, max_length=2000)),
                ("report_format", models.CharField(blank=True, max_length=16)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("summary_json", models.JSONField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sent_at"], name="crawler_rep_sent_at_0d1cf7_idx"
                    ),
                    models.Index(
                        fields=["source_type"], name="crawler_rep_source__efac9a_idx"
                    ),
                    models.Index(
                        fields=["published_at"], name="crawler_rep_publish_3118b9_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="reportitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("report_url", ""), _negated=True),
                fields=("report_url",),
                name="uq_report_url_nonempty",
            ),
        ),
    ]
