# Generated by Django 5.0.7 on 2026-01-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportitem",
            name="ai_ip_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="reportitem",
            name="ai_ip_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportitem",
            name="ai_ip_verified",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportitem",
            name="published_at_raw",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="reportitem",
            name="published_at_source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="reportitem",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
